export const INDIAN_COLLEGES = [
  "Adamas University",
  "AKTU Lucknow",
  "Alagappa University",
  "Allahabad University",
  "Alliance University",
  "Amity University Mumbai",
  "Amity University Noida",
  "Amravati University",
  "AMU Aligarh",
  "Anna University",
  "Annamalai University",
  "APJ Abdul Kalam Technological University (KTU)",
  "Arya College Jaipur",
  "Ashoka University",
  "Azim Premji University",
  "Bangalore University",
  "Bennett University",
  "Bharathiar University",
  "Bharathidasan University",
  "BHU Varanasi",
  "Bishop Cotton Women's Christian College",
  "BITS Goa",
  "BITS Hyderabad",
  "BITS Pilani",
  "BMS College Bangalore",
  "Brihan Maharashtra College of Commerce (BMCC)",
  "Calcutta University",
  "Calicut University",
  "Canara College Mangalore",
  "Career Point University",
  "CEG Chennai",
  "Chandigarh University",
  "Chitkara University",
  "Christ University Bangalore",
  "CMR University",
  "Cochin University of Science and Technology (CUSAT)",
  "COEP Pune",
  "CSVTU Chhattisgarh",
  "DAIICT Gandhinagar",
  "Daulat Ram College Delhi",
  "Dayananda Sagar University",
  "DBATU Maharashtra",
  "Delhi Technological University (DTU)",
  "DIT University",
  "DJ Sanghvi Mumbai",
  "Fergusson College Pune",
  "FLAME University Pune",
  "Galgotias University",
  "Gargi College Delhi",
  "GLA University Mathura",
  "Government Science College Bangalore",
  "Graphic Era University",
  "GTU Gujarat",
  "Hansraj College Delhi",
  "Heritage Institute Kolkata",
  "Hindu College Delhi",
  "Hindustan University",
  "HMT Degree College",
  "Hyderabad University",
  "ICT Mumbai",
  "IFTM University",
  "IIEST Shibpur",
  "IIIT Agartala",
  "IIIT Allahabad",
  "IIIT Bangalore",
  "IIIT Bhagalpur",
  "IIIT Bhopal",
  "IIIT Delhi",
  "IIIT Dharwad",
  "IIIT Guwahati",
  "IIIT Hyderabad",
  "IIIT Kalyani",
  "IIIT Kancheepuram",
  "IIIT Kottayam",
  "IIIT Kurnool",
  "IIIT Lucknow",
  "IIIT Manipur",
  "IIIT Nagpur",
  "IIIT Pune",
  "IIIT Ranchi",
  "IIIT Sonepat",
  "IIIT Sri City",
  "IIIT Srirangam",
  "IIIT Tiruchirappalli",
  "IIIT Una",
  "IIIT Vadodara",
  "IIT Bhilai",
  "IIT Bhubaneswar",
  "IIT Bombay",
  "IIT Delhi",
  "IIT Dhanbad (ISM)",
  "IIT Dharwad",
  "IIT Gandhinagar",
  "IIT Goa",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT Indore",
  "IIT Jammu",
  "IIT Jodhpur",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Madras",
  "IIT Mandi",
  "IIT Palakkad",
  "IIT Patna",
  "IIT Roorkee",
  "IIT Ropar",
  "IIT Tirupati",
  "IMS Ghaziabad",
  "Indraprastha College Delhi",
  "Indraprastha University (GGSIPU)",
  "Invertis University",
  "Jadavpur University",
  "Jain University Bangalore",
  "Jaipur National University",
  "Jamia Millia Islamia",
  "JECRC University",
  "Jesus and Mary College Delhi",
  "JIS University",
  "JNTU Anantapur",
  "JNTU Hyderabad",
  "JNTU Kakinada",
  "Jyoti Nivas College Bangalore",
  "Kalinga University",
  "Kamarajar University",
  "Kannur University",
  "Kerala University",
  "KIIT Bhubaneswar",
  "Kirori Mal College Delhi",
  "KIT Kolhapur",
  "KJ Somaiya Mumbai",
  "KMC Manipal",
  "Krea University",
  "Kristu Jayanti College Bangalore",
  "KU Kurukshetra",
  "Lady Shri Ram College Delhi",
  "Lovely Professional University",
  "Loyola College Chennai",
  "LPU Jalandhar",
  "Lucknow University",
  "Madras Christian College",
  "Madras University",
  "Mahatma Gandhi University Kerala",
  "Manav Rachna University",
  "Manipal College of Arts Science and Commerce",
  "Manonmaniam Sundaranar University",
  "MDU Rohtak",
  "Meghnad Saha Institute",
  "Miranda House Delhi",
  "MIT College of Arts Commerce Science",
  "MIT Manipal",
  "MIT-WPU Pune",
  "MNIT Bhopal",
  "Mody University",
  "Mother Teresa University",
  "Mount Carmel College Bangalore",
  "MSRIT Bangalore",
  "Mumbai University",
  "Nagpur University",
  "National College Bangalore",
  "Netaji Subhas University of Technology (NSUT)",
  "NID Ahmedabad",
  "NIFT Delhi",
  "NIT Agartala",
  "NIT Allahabad (MNNIT)",
  "NIT Andhra Pradesh",
  "NIT Arunachal Pradesh",
  "NIT Calicut",
  "NIT Delhi",
  "NIT Durgapur",
  "NIT Goa",
  "NIT Hamirpur",
  "NIT Jaipur (MNIT)",
  "NIT Jalandhar",
  "NIT Kurukshetra",
  "NIT Manipur",
  "NIT Meghalaya",
  "NIT Mizoram",
  "NIT Nagaland",
  "NIT Nagpur (VNIT)",
  "NIT Patna",
  "NIT Puducherry",
  "NIT Rourkela",
  "NIT Sikkim",
  "NIT Silchar",
  "NIT Srinagar",
  "NIT Surathkal",
  "NIT Trichy",
  "NIT Uttarakhand",
  "NIT Warangal",
  "NMIMS Mumbai",
  "Noida International University",
  "Osmania University",
  "Periyar University",
  "PES Modern College",
  "PES University Bangalore",
  "PICT Pune",
  "Plaksha University",
  "Poornima University",
  "Presidency College Chennai",
  "Presidency College Kolkata",
  "Presidency University Bangalore",
  "PSG College of Technology",
  "PTU Punjab",
  "Pune University (SPPU)",
  "Ramjas College Delhi",
  "RGPV Bhopal",
  "RNS Institute of Technology",
  "Rosario College Mangalore",
  "RTMNU",
  "RTU Rajasthan",
  "RV College Bangalore",
  "Sathyabama University",
  "Saveetha University",
  "SCOE Pune",
  "SCSIT",
  "Sharda University",
  "Shiv Nadar University",
  "Shri Ram College of Commerce Delhi",
  "SIES Mumbai",
  "SIT Pune",
  "SPA Bhopal",
  "SPA Delhi",
  "SPIT Mumbai",
  "SPPU Pune",
  "SRCC Delhi",
  "Sri Balaji University",
  "Sri Venkateswara College Delhi",
  "Sri Venkateswara University",
  "SRM Chennai",
  "SRM Delhi NCR",
  "St. Agnes College Mangalore",
  "St. Aloysius College Mangalore",
  "St. Joseph's College Bangalore",
  "St. Xavier's College Kolkata",
  "St. Xavier's College Mumbai",
  "SVKM's NMIMS",
  "Symbiosis College Pune",
  "Symbiosis Institute Pune",
  "Techno India",
  "Teerthanker Mahaveer University",
  "Thapar Institute of Engineering",
  "THAPAR University Patiala",
  "Thiruvalluvar University",
  "UPES Dehradun",
  "Utkal University",
  "Vel Tech University",
  "VIT AP",
  "VIT Bhopal",
  "VIT Chennai",
  "VIT Vellore",
  "VJTI Mumbai",
  "VTU Karnataka",
  "Wadia College Pune",
  "Walchand College Sangli",
  "Women's Christian College Chennai",
  "YCMOU",
  "Other"
];

export const BRANCHES = [
  {
    category: "Engineering & Technology",
    options: [
      "Computer Science & Engineering (CSE)", "Information Technology (IT)", 
      "CSE – AI & ML", "CSE – Data Science", "CSE – Cybersecurity", 
      "CSE – Cloud Computing", "CSE – IoT", "Electronics & Communication Engineering (ECE)", 
      "Electrical Engineering (EE)", "Electrical & Electronics Engineering (EEE)", 
      "Mechanical Engineering", "Civil Engineering", "Chemical Engineering", 
      "Aerospace / Aeronautical Engineering", "Biotechnology Engineering", 
      "Biomedical Engineering", "Industrial Engineering", "Production Engineering", 
      "Automobile Engineering", "Marine Engineering", "Mining Engineering", 
      "Metallurgical Engineering", "Environmental Engineering", "Agricultural Engineering", 
      "Food Technology", "Textile Engineering", "Instrumentation Engineering", 
      "Robotics & Automation", "Artificial Intelligence", "Data Science", 
      "Cyber Security", "Software Engineering"
    ]
  },
  {
    category: "Science",
    options: [
      "B.Sc. Computer Science", "B.Sc. IT", "B.Sc. Mathematics", "B.Sc. Physics", 
      "B.Sc. Chemistry", "B.Sc. Biology / Life Sciences", "B.Sc. Microbiology", 
      "B.Sc. Biotechnology", "B.Sc. Statistics", "B.Sc. Electronics", 
      "B.Sc. Environmental Science", "B.Sc. Forensic Science", "B.Sc. Nursing", 
      "B.Sc. Agriculture", "B.Sc. Horticulture", "BCA (Bachelor of Computer Applications)", 
      "MCA (Master of Computer Applications)"
    ]
  },
  {
    category: "Commerce & Business",
    options: [
      "B.Com General", "B.Com (Hons.)", "BBA", "BMS (Bachelor of Management Studies)", 
      "BBM", "MBA", "CA (Chartered Accountancy)", "CMA", "CS (Company Secretary)", 
      "B.Com – Banking & Finance", "B.Com – Accounting & Taxation", "B.Com – Marketing", 
      "BFIA (Finance & Investment Analysis)", "BAF (Accounting & Finance)", 
      "BBI (Banking & Insurance)"
    ]
  },
  {
    category: "Arts & Humanities",
    options: [
      "BA English", "BA History", "BA Political Science", "BA Economics", "BA Sociology", 
      "BA Psychology", "BA Philosophy", "BA Geography", "BA Journalism & Mass Communication", 
      "BA Hindi", "BA Sanskrit", "BA Social Work", "BA Foreign Languages", "BA Fine Arts", 
      "BA Fashion Design", "BA Interior Design", "BFA (Bachelor of Fine Arts)", 
      "BDes (Bachelor of Design)", "B.Arch (Architecture)"
    ]
  },
  {
    category: "Medical & Health Sciences",
    options: [
      "MBBS", "BDS (Dental)", "BAMS (Ayurveda)", "BHMS (Homeopathy)", "BUMS (Unani)", 
      "B.Pharmacy", "D.Pharmacy", "BPT (Physiotherapy)", "BOT (Occupational Therapy)", 
      "B.Sc. Radiology", "B.Sc. Medical Lab Technology", "B.Sc. Optometry", "Pharm.D", "BMLT"
    ]
  },
  {
    category: "Law",
    options: ["BA LLB", "BBA LLB", "B.Com LLB", "LLB (3-year)", "LLM"]
  },
  {
    category: "Education",
    options: ["B.Ed", "D.El.Ed", "B.P.Ed", "B.El.Ed", "B.Lib"]
  },
  {
    category: "Other / Vocational",
    options: [
      "Diploma – Civil", "Diploma – Mechanical", "Diploma – ECE", "Diploma – CS", 
      "Polytechnic (General)", "Hotel Management (BHM)", "Travel & Tourism", 
      "Event Management", "Media Studies"
    ]
  }
];

export const SEMESTERS = [
  "1st Semester / 1st Year",
  "2nd Semester / 1st Year",
  "3rd Semester / 2nd Year",
  "4th Semester / 2nd Year",
  "5th Semester / 3rd Year",
  "6th Semester / 3rd Year",
  "7th Semester / 4th Year",
  "8th Semester / 4th Year",
  "9th Semester (5-year program)",
  "10th Semester (5-year program)",
  "Other / Not applicable"
];
