"use client";

import { useEffect, useState } from "react";
import { WeeklyGrid } from "@/components/timetable/WeeklyGrid";
import { ExportButton } from "@/components/timetable/ExportButton";
import { TimetableData, TimetableSlot } from "@/lib/types";
import { ArrowLeft, Clock } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function TimetablePage() {
  const router = useRouter();
  const [data, setData] = useState<TimetableData | null>(null);

  useEffect(() => {
    const saved = localStorage.getItem("studyforge_timetable");
    if (saved) {
      try {
        // eslint-disable-next-line react-hooks/set-state-in-effect
        setData(JSON.parse(saved));
      } catch (e) {
        console.error("Failed to load timetable", e);
      }
    } else {
      router.push("/create");
    }
  }, [router]);

  const handleUpdateSlot = (day: string, time: string, updated: TimetableSlot) => {
    setData(prev => {
      if (!prev) return prev;
      const _new = { ...prev };
      _new.grid[day][time] = updated;
      localStorage.setItem("studyforge_timetable", JSON.stringify(_new));
      return _new;
    });
  };

  if (!data) return (
    <div className="min-h-screen bg-slate-950 flex flex-col items-center justify-center p-4">
      <Clock className="w-12 h-12 text-teal-500 animate-spin mb-4" />
      <p className="text-white">Loading your perfect week...</p>
    </div>
  );

  return (
    <div className="min-h-screen bg-slate-950 p-4 sm:p-8 flex flex-col items-center">
      <div className="w-full max-w-7xl">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-8 pb-4 border-b border-white/10 gap-4">
          <div>
            <Link href="/create">
              <span className="text-slate-400 hover:text-white flex items-center text-sm font-medium transition-colors mb-2">
                <ArrowLeft className="w-4 h-4 mr-1" /> New Timetable
              </span>
            </Link>
            <h1 className="text-3xl font-extrabold text-white tracking-tight">{data.title || "My Perfect Semester"}</h1>
            <p className="text-teal-400 font-medium text-sm mt-1">Generated by StudyForge AI</p>
          </div>
          
          <div className="flex items-center gap-3">
            <ExportButton targetId="timetable-container" />
          </div>
        </div>

        <div id="timetable-container" className="p-4 sm:p-6 bg-slate-950 rounded-2xl relative border border-white/5 shadow-[0_0_100px_rgba(45,212,191,0.05)]">
           <WeeklyGrid data={data} onUpdateSlot={handleUpdateSlot} />
           {/* Watermark for export visible only during export via id context if preferred, or subtly visible */}
           <div className="pt-6 pb-2 text-center text-xs text-white/20 font-mono tracking-widest uppercase">
             studyforge.ai
           </div>
        </div>
      </div>
    </div>
  );
}
